import type { ContactFormData } from '@/app/contacte/types/form.types';

export const baseValidForm: ContactFormData = {
  name: 'Anna García',
  email: 'anna@example.com',
  phone: '',
  location: '',
  serviceType: 'general',
  arttherapyFormat: '',
  participantAge: '',
  schoolName: '',
  educationStage: '',
  studentsCount: '',
  courseGroup: '',
  courseInterest: '',
  externsSubtype: '',
  centreSubtype: '',
  teachersCount: '',
  trainingInterest: '',
  entityType: '',
  entityName: '',
  entityDescription: '',
  participantsCount: '',
  projectDescription: '',
  message: 'Hola, vull demanar informació sobre els serveis.',
  contactPreference: [],
  availability: '',
  privacyAccepted: true,
  website: '',
};
