"use server"

/**
 * Response structure from Google reCAPTCHA Enterprise API
 * Based on official documentation
 */
interface RecaptchaEnterpriseResponse {
  name: string;
  event: {
    token: string;
    siteKey: string;
    userAgent?: string;
    userIpAddress?: string;
    expectedAction: string;
  };
  riskAnalysis: {
    score: number;
    reasons: string[];
    challenge?: 'PASS' | 'FAIL' | 'NOCAPTCHA';
  };
  tokenProperties: {
    valid: boolean;
    invalidReason?: string;
    hostname: string;
    action: string;
    createTime: string;
  };
}

interface VerifyRecaptchaResult {
  success: boolean;
  score?: number;
  error?: string;
}

/**
 * Verifies reCAPTCHA Enterprise token with Google's API
 * 
 * Uses the SECRET API KEY that never leaves the server
 * Follows Google's official reCAPTCHA Enterprise documentation
 * 
 * @param token - The reCAPTCHA token generated by grecaptcha.enterprise.execute()
 * @returns Object with verification result and risk score
 */
export async function verifyRecaptcha(token: string): Promise<VerifyRecaptchaResult> {
  const secretKey = process.env.RECAPTCHA_SECRET_KEY;
  const projectId = process.env.RECAPTCHA_PROJECT_ID;
  const siteKey = process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY;

  // Validate configuration
  if (!secretKey) {
    console.error('❌ RECAPTCHA_SECRET_KEY not configured in environment variables');
    return {
      success: false,
      error: 'Configuració de reCAPTCHA incompleta (secret key)'
    };
  }

  if (!projectId) {
    console.error('❌ RECAPTCHA_PROJECT_ID not configured in environment variables');
    return {
      success: false,
      error: 'Configuració de reCAPTCHA incompleta (project ID)'
    };
  }

  if (!siteKey) {
    console.error('❌ NEXT_PUBLIC_RECAPTCHA_SITE_KEY not configured in environment variables');
    return {
      success: false,
      error: 'Configuració de reCAPTCHA incompleta (site key)'
    };
  }

  try {
    // Build the Google reCAPTCHA Enterprise API URL
    // Format: https://recaptchaenterprise.googleapis.com/v1/projects/{project}/assessments?key={api_key}
    const url = `https://recaptchaenterprise.googleapis.com/v1/projects/${projectId}/assessments?key=${secretKey}`;
    
    // Make the API call to verify the token
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        event: {
          token: token,
          expectedAction: 'SUBMIT_CONTACT_FORM',
          siteKey: siteKey,
        },
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('❌ reCAPTCHA API error:', {
        status: response.status,
        statusText: response.statusText,
        error: errorText
      });
      return {
        success: false,
        error: 'Error en la verificació de reCAPTCHA'
      };
    }

    const data: RecaptchaEnterpriseResponse = await response.json();

    // Check if token is valid
    if (!data.tokenProperties?.valid) {
      console.warn('⚠️ reCAPTCHA token invalid:', {
        invalidReason: data.tokenProperties?.invalidReason,
        hostname: data.tokenProperties?.hostname,
        action: data.tokenProperties?.action
      });
      return {
        success: false,
        error: 'Token de reCAPTCHA invàlid'
      };
    }

    // Get risk score (0.0 = very likely bot, 1.0 = very likely human)
    const score = data.riskAnalysis?.score ?? 0;

    // Log verification details for monitoring
    console.log('✅ reCAPTCHA Enterprise verified:', {
      score,
      valid: data.tokenProperties.valid,
      action: data.tokenProperties.action,
      expectedAction: 'SUBMIT_CONTACT_FORM',
      hostname: data.tokenProperties.hostname,
      challenge: data.riskAnalysis?.challenge,
      reasons: data.riskAnalysis?.reasons || []
    });

    // Threshold: reject if score is below 0.5
    // Adjust this threshold based on your needs:
    // - 0.3: More strict (may block some legitimate users)
    // - 0.5: Balanced (recommended)
    // - 0.7: More lenient (may allow some bots)
    const SCORE_THRESHOLD = 0.5;
    
    if (score < SCORE_THRESHOLD) {
      console.warn('🚨 Low reCAPTCHA score detected:', {
        score,
        threshold: SCORE_THRESHOLD,
        reasons: data.riskAnalysis?.reasons || []
      });
      return {
        success: false,
        score,
        error: 'Verificació de seguretat fallida'
      };
    }

    return {
      success: true,
      score
    };

  } catch (error) {
    console.error('❌ reCAPTCHA verification exception:', error);
    return {
      success: false,
      error: 'Error inesperat en la verificació'
    };
  }
}
